import React from "react";
import Provider from "@/app/provider";
import "@/styles/globals.css"
import TopNavBar from "@/components/layout/TopNavBar";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Provider>
            <TopNavBar/>
            {children}
        </Provider>
        </body>
        </html>
    )
}