import React from "react";
import Provider from "@/app/provider";
import "@/styles/globals.css"
import SessionStatus from "@/components/layout/SessionStatus";
import {Providers} from "@/app/providers";
import NewNavBar from "@/components/ui/NewNavBar";
import Footer from "@/components/ui/footer";
import {Toaster} from "react-hot-toast";

export const metadata = {
    title: 'MiloNite.app',
    description: 'Generated by Next.js',
}


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="light">
        <body style={{backgroundColor:"#fff"}}>
        <Provider>
          <SessionStatus>
              <Providers >
                  <NewNavBar/>
                  {children}
                  <Toaster position="top-right" reverseOrder={false} />
                  <Footer/>
              </Providers>
          </SessionStatus>
        </Provider>
        </body>
        </html>
    )
}