import React from "react";


export const metadata = {
    title: 'MiloNite.app',
    description: 'Generated by Next.js',
}


export default function AdminLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <div>{children}</div>
    )
}